version: '3.1'

services:
  tomocero:
    image: voko-tomocero
    build: 
      context: .
      dockerfile: Dockerfile
    command: /usr/lib/postfix/master -d
    volumes:
      # eble ni eksterigu ankaŭ /var/spool/postfix resp. tutan /var/spool
      - mail:/var/mail
      - spool:/var/spool
    secrets:
      - voko-tomocero.pop3_server
      - voko-tomocero.pop3_user
      - voko-tomocero.pop3_password
      - voko-tomocero.myhostname
      - voko-tomocero.saslpassword
      - voko-tomocero.relayhost
      - voko-tomocero.relayaddress
      - voko-tomocero.relaypassword

secrets:
  voko-tomocero.pop3_server:
    external: true
  voko-tomocero.pop3_user:
    external: true
  voko-tomocero.pop3_password:
    external: true
  voko-tomocero.myhostname:
    external: true
  voko-tomocero.saslpassword:
    external: true
  voko-tomocero.relayhost:
    external: true
  voko-tomocero.relayaddress:
    external: true
  voko-tomocero.relaypassword:
    external: true

volumes:
  mail:
  spool:
  


